### ISSUE TITLE
Incomplete Release Notes inside mail

### ISSUE THREAD

**Issue by FabioPedretti** [vfeskov/gitpunch#45] opened 2018-07-20 14:37 UTC
I am subscribed to both Gitpunch and CodeRelease.io. Gitpunch often sends empty releases notes, while I get proper notes with CodeRelease.io.

I am not sure, but maybe the release notes are added by the developers after some time the release is created, so the mail is sent empty (I noticed CodeRelease.io sends the mail later than Gitpunch). Maybe adding 24h before sending the mail (#33) could be useful to prevent this?

See this example for the same software release.
Thanks.

Gitpunch:

> ---------- Forwarded message ---------
> From: <releases@gitpunch.com>
> Date: mer 18 lug 2018 alle ore 11:23
> Subject: suricata@suricata-4.0.5
> 
> OISF/suricata@suricata-4.0.5
> GitHub
> 
> Tag 4.0.5 release
> Best wishes from Vlad @ GitPunch
> Support me with a star
> This is an automated message, reply if you have any questions
> To stop getting these emails click unsubscribe

CodeRelease.io:

> ---------- Forwarded message ---------
> From: CodeRelease.io <no-reply@coderelease.io>
> Date: gio 19 lug 2018 alle ore 04:43
> Subject: 📩 OISF/suricata suricata-4.0.5 released
> 
> OISF/suricata suricata-4.0.5
> 
> View Release: https://github.com/OISF/suricata/releases/tag/suricata-4.0.5
> Release Notes
> 
> https://suricata-ids.org/2018/07/18/suricata-4-0-5-available/
> Redmine Tracker
> 
> https://redmine.openinfosecfoundation.org/versions/111
> Download
> 
> https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz
> 
> https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz.sig
> Documentation
> 
> https://suricata.readthedocs.io/en/suricata-4.0.5/
> 
> Did you find useful this notification? Make a donation for supporting CodeRelease.io
> 
> Unsubscribe from OISF/suricata release notifications (no login required)

**Comment by vfeskov** [comment] 2018-07-20 15:04
duplicate of #32 , this happens because sometimes people make a release with no description and put the description later. GitPunch sends emails based on GitHub's public events, and once a release is published - email follows shortly after, and sometimes there's no description yet to put in the email

**Closed by vfeskov** 2018-07-20 15:04 UTC
